# config.yaml

# Device settings
device: "cuda:0"  # If available, otherwise CPU will be used in the script

# Path to dataset
data_paths:
  - "../LMDB_INPUT/Generated128x128_cryospin/"

# Training parameters
batch_size: 32
epochs: 50

defocus_values : [230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310, 312, 314, 316, 318, 320, 322, 324, 326, 328]
classes_num : 50



noise_dim: 100
dim: 16  
lr: 0.0001
beta_1: 0.9
beta_2: 0.99
img_size: [256, 256, 1]
print_every: 5000
standarization: False
gaussian_filter: 0.025
critic_iterations: 5
gp_weight: 10
checkpoint_dir: 30
save_checkpoint_every: 2500
# WandB settings
wandb:
  project: "Defocus-Classifier"
  architecture: "CNN regressor, MeanSquaredErrorLoss"
  dataset: "10K_Particles"
  run_id: '20/3/25: cryoSPIN NO DECIMALS data 5 convs CNN regressor less hyperparameters, MeanSquaredErrorLoss___lr=1e-4, 50 EPOCHS normalization and weight init_WITH check for overfit'
